export const DEPARTEMENTLOAD = "DEPARTEMENTLOAD"

export const DEPARTEMENTSUCC = "DEPARTEMENTSUCC"

export const DEPARTEMENTFAIL = "DEPARTEMENTFAIL"

export const LISTDEPARTEMENTSUCC = "LISTDEPARTEMENTSUCC"


