export const SOLDELOAD = "SOLDELOAD"

export const SOLDESUCC = "SOLDESUCC"

export const SOLDEFAIL = "SOLDEFAIL"

export const LISTSOLDESUCC = "LISTSOLDESUCC"

export const LISTMYSOLDESUCC = "LISTMYSOLDESUCC"