export const DEMANDELOAD = "DEMANDELOAD"

export const DEMANDESUCC = "DEMANDESUCC"

export const DEMANDEFAIL = "DEMANDEFAIL"

export const LISTDEMANDESUCC = "LISTDEMANDESUCC"

export const LISTDEMANDEADSUCC = "LISTDEMANDEADSUCC"
export const LISTDEMANDEMASUCC = "LISTDEMANDEMASUCC"
export const LISTDEMANDEMYSUCC = "LISTDEMANDEMYSUCC"
