apiVersion: apps/v1
kind: Deployment
metadata: #Dictionary
  name: node-app
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata: # Dictionary
      name: node-app
      labels: # Dictionary
        app: node-app  # Key value pairs
    spec:
      containers: # List
        - name: backend
          image: 002710867275.dkr.ecr.us-east-1.amazonaws.com/backend:3
          ports:
            - containerPort: 8000
