apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: node-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: node-app
status:
  loadBalancer: {}
