export const ETABLISSEMENTLOAD = "ETABLISSEMENTLOAD"

export const ETABLISSEMENTSUCC = "ETABLISSEMENTSUCC"

export const ETABLISSEMENTFAIL = "ETABLISSEMENTFAIL"

export const LISTETABLISSEMENTSUCC = "LISTETABLISSEMENTSUCC"


