export const LOGINUSERSUCC = "LOGINUSERSUCC"
export const LOGINFAILD = "LOGINFAILD"
export const LOGOUT = "LOGOUT"

export const USERLOAD = "ADDUSERLOAD"
export const USERSUCC = "ADDUSERSUCC"
export const USERFAIL = "ADDUSERFAIL"

export const LISTUSERSUCC = "LISTUSERSUCC"
export const LISTCLIENTSUCC = "LISTCLIENTSUCC"
export const LISTMANAGERSUCC = "LISTMANAGERSUCC"
export const LISTALLSUCC = "LISTALLSUCC"

export const EDITUSERFAIL = "EDITUSERFAIL"
export const EDITUSERSUCC = "EDITUSERSUCC"
export const DELETEUSERSUCC = "DELETEUSER"
export const DELETEUSERFAIL = "DELETEUSER"

export const EDITUERPASSWORDSUCC = "EDITUERPASSWORDSUCC"
export const EDITUSERPASSWORDFAIL = "EDITUERPASSWORDFAIL"
export const GETONEUSERSUCC = "GETONEUSERSUCC"
export const GETONEUSERFAIL = "GETONEUSERFAIL"
export const REGISTERUSER = "GETONEUSERFAIL"
export const REGISTERUSERFAIL = "GETONEUSERFAIL"

export const CURRENT_USER = "CURRENT_USER"
